### ISSUE TITLE
[Question] I can't fuse the output with origin?

### ISSUE THREAD

**Issue by YukiSakuma** [makegirlsmoe/crypko#12]
Crpyko 1 fused with Crypko 2
to create
Crypko 3 output
I can't fuse Crypko 3 with Crypko 2 or 1?

**Comment by hanezu** [comment]
Repeatedly fusing a Crypko with its origins will lead to convergence in appearance, so we banned it.

**Comment by YukiSakuma** [comment]
I see, thanks
