### ISSUE TITLE
Crypko has an unfamiliar derivative

### ISSUE THREAD

**Issue by Chocobana** [makegirlsmoe/crypko#7]
I noticed my crypko(first pic) has an unfamiliar derivative(second pic) with different origins unrelated to mine. 
So heres the link:

https://crypko.ai/#/card/207717 (My Crypko)
![bug1](https://user-images.githubusercontent.com/39990282/41033825-62123f48-69ba-11e8-8e32-2bc9ff146da1.png)

https://crypko.ai/#/card/207930 (Derivative)
![bug2](https://user-images.githubusercontent.com/39990282/41033827-63a8a4f0-69ba-11e8-8f42-f80bb766ff73.png)

**Comment by hanezu** [comment]
Thank you very much for reporting the issue! It is fixed now.
